require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '12.0'
use_modular_headers!

target 'CempakaNew' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    :hermes_enabled => false,
  )

   # Firebase pods
  pod 'GoogleUtilities'
  pod 'RNImageCropPicker', :path => '../node_modules/react-native-image-crop-picker'
  # Add this line to include FBReactNativeSpec
  pod 'FBReactNativeSpec', :path => "../node_modules/react-native/React/FBReactNativeSpec"
  pod 'RNFirebase', :path => '../node_modules/react-native-firebase/ios'
  pod 'Firebase/Core', '~> 6.3.0'
  # pod 'Firebase/Auth'
  pod 'Firebase/Analytics'


  target 'CempakaNewTests' do
    inherit! :complete
  end

  post_install do |installer|
    react_native_post_install(installer)
    
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings["IPHONEOS_DEPLOYMENT_TARGET"] = "12.0"
        
        # Disable UIWebView
        config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= ['$(inherited)']
        config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] << 'DISABLE_UIWEBVIEW=1'
        
        # Force WKWebView
        if target.name.include?('React-Core')
          config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] << 'RCT_USE_WKWEBVIEW=1'
        end

        # Tambahkan ini untuk M1 Mac support
        config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = 'arm64'
      end
    end
  end
end